package principal;

import gui.GerarDigitoVerificadorImovel;
import gui.RelatorioBackup;
import gui.cadSQL;
import gui.cadconexoes;
import gui.cadlayout;
import gui.cadusuar;
import util.Util;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

public class Principal extends javax.swing.JFrame {

    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    private Login login;

    public Principal(Login l) {
        login = l;
        initComponents();
        maximizarTela();
        logo();
        UsuarioLogin();
        controlaTempo();

    }

    public void maximizarTela() {
        setExtendedState(Principal.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lb_logo = new javax.swing.JLabel();
        lb_usuarioLogado = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        lb_TpUsuario = new javax.swing.JLabel();
        lb_Situacao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_hora = new javax.swing.JLabel();
        lb_data = new javax.swing.JLabel();
        lb_cdUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        barra_menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItem_Conexoes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuItem_cdbarras = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menu_IS = new javax.swing.JMenu();
        menuItem_IS = new javax.swing.JMenuItem();
        menu_script1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes - LogPro");

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Desenvolvido por: Eduardo Yucho");

        lb_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fonte.jpg"))); // NOI18N

        lb_usuarioLogado.setText("Usuário Logado: ");

        lb_usuario.setText("Eduardo");

        lb_TpUsuario.setText("Eduardo");

        lb_Situacao.setText("Eduardo");

        jLabel2.setText("/");

        jLabel3.setText("/");

        lb_hora.setText("jLabel4");

        lb_data.setText("jLabel5");

        lb_cdUsuario.setText("jLabel4");

        jLabel5.setText("-");

        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_logo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_usuarioLogado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_TpUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_Situacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_hora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_data, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lb_cdUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                        .addComponent(lb_usuarioLogado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_cdUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_TpUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_Situacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_hora)))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_hora)
                    .addComponent(lb_data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lb_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_usuarioLogado)
                    .addComponent(lb_usuario)
                    .addComponent(lb_TpUsuario)
                    .addComponent(lb_Situacao)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lb_cdUsuario)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jMenu1.setText("Sistema");

        menuItem_sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        menuItem_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete_32x32.png"))); // NOI18N
        menuItem_sair.setText("Sair");
        menuItem_sair.setToolTipText("");
        menuItem_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_sairActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_sair);

        barra_menu.add(jMenu1);

        jMenu2.setText("Conexões");

        menuItem_Conexoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItem_Conexoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Picture_32x32.png"))); // NOI18N
        menuItem_Conexoes.setText("Conexões");
        menuItem_Conexoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ConexoesActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem_Conexoes);

        barra_menu.add(jMenu2);

        jMenu3.setText("Cadastros");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User_32x32.png"))); // NOI18N
        jMenuItem1.setText("Usuarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Paste_32x32.png"))); // NOI18N
        jMenuItem3.setText("SQL");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        barra_menu.add(jMenu3);

        jMenu5.setText("Layout");

        jMenu6.setText("Código de barras");

        menuItem_cdbarras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuItem_cdbarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Copy_32x32.png"))); // NOI18N
        menuItem_cdbarras.setText("Código de Barras - G");
        menuItem_cdbarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_cdbarrasActionPerformed(evt);
            }
        });
        jMenu6.add(menuItem_cdbarras);

        jMenu5.add(jMenu6);

        jMenu7.setText("Débito Automático");
        jMenu5.add(jMenu7);

        menu_IS.setText("Impressão Simultânea");

        menuItem_IS.setText("Impressão Simultânea");
        menu_IS.add(menuItem_IS);

        jMenu5.add(menu_IS);

        barra_menu.add(jMenu5);

        menu_script1.setText("Backups");

        jMenuItem2.setText("Relatório");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_script1.add(jMenuItem2);

        barra_menu.add(menu_script1);

        jMenu4.setText("Processos");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Copy_32x32.png"))); // NOI18N
        jMenuItem4.setText("Gerar Código de Débito Automático");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        barra_menu.add(jMenu4);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_ConexoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ConexoesActionPerformed
        cadconexoes cc = new cadconexoes(desktop, null);
        desktop.add(cc);
        cc.setVisible(true);
        Util.centralizarTela(desktop, cc);
    }//GEN-LAST:event_menuItem_ConexoesActionPerformed

    private void menuItem_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItem_sairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cadusuar cc = new cadusuar(desktop);
        desktop.add(cc);
        cc.setVisible(true);
        Util.centralizarTela(desktop, cc);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        cadSQL sql = new cadSQL(desktop);
        desktop.add(sql);
        sql.setVisible(true);
        Util.centralizarTela(desktop, sql);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuItem_cdbarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_cdbarrasActionPerformed
        cadlayout layout = new cadlayout();
        desktop.add(layout);
        layout.setVisible(true);
        Util.centralizarTela(desktop, layout);        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_cdbarrasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        RelatorioBackup rel = new RelatorioBackup(null, true);
        rel.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        GerarDigitoVerificadorImovel modulo11 = new GerarDigitoVerificadorImovel(desktop);
        desktop.add(modulo11);
        modulo11.setVisible(true);
        Util.centralizarTela(desktop, modulo11);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lb_Situacao;
    private javax.swing.JLabel lb_TpUsuario;
    private javax.swing.JLabel lb_cdUsuario;
    private javax.swing.JLabel lb_data;
    private javax.swing.JLabel lb_hora;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JLabel lb_usuarioLogado;
    private javax.swing.JMenuItem menuItem_Conexoes;
    private javax.swing.JMenuItem menuItem_IS;
    private javax.swing.JMenuItem menuItem_cdbarras;
    private javax.swing.JMenuItem menuItem_sair;
    private javax.swing.JMenu menu_IS;
    private javax.swing.JMenu menu_script1;
    // End of variables declaration//GEN-END:variables

    public void logo() {
        lb_logo.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void UsuarioLogin() {

        lb_usuario.setText(login.usuarioLog);
        lb_TpUsuario.setText(login.tpUsuario);
        lb_Situacao.setText(login.stSituacao);
        lb_cdUsuario.setText(Integer.toString(login.cdCodigo));
    }

    public void controlaTempo() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        String data1;
                        data1 = sdf.format(new Date());
                        lb_data.setText(data1.substring(0, data1.indexOf(" ")));
                        lb_hora.setText(data1.substring(data1.indexOf(" ") + 1));
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
    }

}
