/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Eduardo
 */
public class AtualizarIdentificarClienteBco extends javax.swing.JInternalFrame {

    /**
     * Creates new form AtualizarIdentificarClienteBco
     */
    public AtualizarIdentificarClienteBco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_fechar = new javax.swing.JButton();
        bt_selecionarArqArrecadacao = new javax.swing.JButton();
        bt_selecionarDestino = new javax.swing.JButton();
        txt_caminhoArquivo = new javax.swing.JTextField();
        txt_caminhoDestino = new javax.swing.JTextField();
        bt_gerar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Atualizar Identificação do Cliente no Banco");

        bt_fechar.setText("Fechar");

        bt_selecionarArqArrecadacao.setText("Selecionar");

        bt_selecionarDestino.setText("Selecionar");

        bt_gerar.setText("Gerar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 315, Short.MAX_VALUE)
                        .addComponent(bt_gerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_fechar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_selecionarDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_caminhoDestino))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_selecionarArqArrecadacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_caminhoArquivo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_selecionarArqArrecadacao)
                    .addComponent(txt_caminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_selecionarDestino)
                    .addComponent(txt_caminhoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_fechar)
                    .addComponent(bt_gerar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_gerar;
    private javax.swing.JButton bt_selecionarArqArrecadacao;
    private javax.swing.JButton bt_selecionarDestino;
    private javax.swing.JTextField txt_caminhoArquivo;
    private javax.swing.JTextField txt_caminhoDestino;
    // End of variables declaration//GEN-END:variables
}
