/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JDesktopPane;

/**
 *
 * @author Eduardo
 */
public class GerarDigitoVerificadorImovel extends javax.swing.JInternalFrame {

    private JDesktopPane desktop;
    public GerarDigitoVerificadorImovel(JDesktopPane desktop) {
        this.desktop = desktop;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_imoveis = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_resultado = new javax.swing.JTextArea();
        bt_fechar = new javax.swing.JButton();
        bt_gerar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerar dígito do módulo 11");

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        txt_imoveis.setColumns(20);
        txt_imoveis.setLineWrap(true);
        txt_imoveis.setRows(5);
        txt_imoveis.setBorder(javax.swing.BorderFactory.createTitledBorder("Imóveis"));
        jScrollPane1.setViewportView(txt_imoveis);

        txt_resultado.setColumns(20);
        txt_resultado.setRows(5);
        txt_resultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jScrollPane2.setViewportView(txt_resultado);

        bt_fechar.setText("Fechar");
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });

        bt_gerar.setText("Gerar");
        bt_gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1179, Short.MAX_VALUE)
                        .addComponent(bt_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_gerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_fechar))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_fechar)
                    .addComponent(bt_limpar)
                    .addComponent(bt_gerar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        txt_resultado.setText("");
    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_fecharActionPerformed

    private void bt_gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerarActionPerformed
        String imoveisDigitados = txt_imoveis.getText();
        String[] vals = imoveisDigitados.split(",");
        obterDigitoVerificadorModulo11(vals);
    }//GEN-LAST:event_bt_gerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_gerar;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_imoveis;
    private javax.swing.JTextArea txt_resultado;
    // End of variables declaration//GEN-END:variables

        public void retornarResultado(String resultado) {
        txt_resultado.append("\r\n" + resultado);
    }
    
    public void obterDigitoVerificadorModulo11(String... numero) {
        for (String wnumero : numero) {
            
            int param = 2;
            int soma = 0;
            
            for (int ind = (wnumero.length() - 1); ind >= 0; ind--) {
                if (param > 9) {
                    param = 2;
                }
                soma = soma + (Integer.parseInt(wnumero.substring(ind, ind + 1)) * param);
                param = param + 1;
            }
            
            int resto = soma % 11;
            int dv;
            
            if ((resto == 0) || (resto == 1)) {
                dv = 0;
            } else {
                dv = 11 - resto;
            }
            retornarResultado("UPDATE cadastro.imovel set imov_cddebitoautomatico = " + wnumero + dv + ", imov_tmultimaalteracao = now(), imov_cddebitoautoespecial = NULL WHERE imov_id = " + wnumero + ";");
            System.out.println("Resultado: " + wnumero + dv);
            
        }        
    }

}
