/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.alteracoesDAO;
import vo.alteracoesVO;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Eduardo
 */
public class visualizarAlteracao extends javax.swing.JInternalFrame {

    /**
     * Creates new form visualizarAlteracao
     */
    public visualizarAlteracao(int codVisualizar, int i) {
        initComponents();
        Esc();
        txt_visualizaAlteracao.setLineWrap(true);

        if (i == 1) {
            consultar(codVisualizar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_fechar = new javax.swing.JButton();
        lb_visualizaCodigo = new javax.swing.JLabel();
        txt_visualizaCodigo = new javax.swing.JTextField();
        lb_visualizaTecnico = new javax.swing.JLabel();
        txt_visualizaTecnico = new javax.swing.JTextField();
        lb_visualizaData = new javax.swing.JLabel();
        txt_visualizaData = new javax.swing.JTextField();
        lb_visualizaAlteracao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_visualizaAlteracao = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txt_visualizaCodCidade = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Visualizar Alteração");

        bt_fechar.setText("Fechar");
        bt_fechar.setPreferredSize(new java.awt.Dimension(65, 30));
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });

        lb_visualizaCodigo.setText("Código: ");

        txt_visualizaCodigo.setEditable(false);

        lb_visualizaTecnico.setText("Técnico: ");

        txt_visualizaTecnico.setEditable(false);

        lb_visualizaData.setText("Data: ");

        txt_visualizaData.setEditable(false);

        lb_visualizaAlteracao.setText("Alteração: ");

        txt_visualizaAlteracao.setEditable(false);
        txt_visualizaAlteracao.setColumns(20);
        txt_visualizaAlteracao.setRows(5);
        jScrollPane1.setViewportView(txt_visualizaAlteracao);

        jLabel1.setText("Cód. da Cidade:");

        txt_visualizaCodCidade.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_visualizaTecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_visualizaTecnico))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_visualizaAlteracao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_visualizaCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_visualizaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_visualizaData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_visualizaData, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_visualizaCodCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_visualizaCodigo)
                    .addComponent(txt_visualizaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_visualizaData)
                    .addComponent(txt_visualizaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_visualizaCodCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_visualizaTecnico)
                    .addComponent(txt_visualizaTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_visualizaAlteracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        this.dispose();

    }//GEN-LAST:event_bt_fecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_visualizaAlteracao;
    private javax.swing.JLabel lb_visualizaCodigo;
    private javax.swing.JLabel lb_visualizaData;
    private javax.swing.JLabel lb_visualizaTecnico;
    private javax.swing.JTextArea txt_visualizaAlteracao;
    private javax.swing.JTextField txt_visualizaCodCidade;
    private javax.swing.JTextField txt_visualizaCodigo;
    private javax.swing.JTextField txt_visualizaData;
    private javax.swing.JTextField txt_visualizaTecnico;
    // End of variables declaration//GEN-END:variables

    private void consultar(int cod) {
        alteracoesVO altVO = new alteracoesDAO().consultar(cod);

        txt_visualizaCodigo.setText(Integer.toString(altVO.getCd_alteracao()));
        txt_visualizaCodCidade.setText(Integer.toString(altVO.getCd_cadastro()));
        txt_visualizaAlteracao.setText(altVO.getDs_alteracao());
        txt_visualizaData.setText(String.valueOf(altVO.getDt_data()));
        txt_visualizaTecnico.setText(altVO.getNm_tecnico());
    }
//-------------------------------------------------------------------------------------------------

    public void Esc() {

        bt_fechar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Esc");
        bt_fechar.getActionMap().put("Esc", new AbstractAction() {

            @Override

            public void actionPerformed(ActionEvent e) {
                fecharTela();
            }
        });
    }
 //----------------------------------------------------------------------------------------------------------------
    private void fecharTela(){
        this.dispose();
    }

}
